Repository acelera5-g3/carango-bom-base, pull requests merged in 2021-07, with the labels that each got.

#2 Teste
  .eslintignore
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.js
  src/components/Rodape/index.jsx
  src/hooks/useErros.js
  src/index.js
  src/pages/CadastroMarca.jsx
  src/pages/ListagemMarcas.jsx
  src/reportWebVitals.js
  src/services/MarcaService.js
  src/services/VeiculoService.js
Labels: bug

#1 Create menu
  .eslintignore
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.js
  src/components/Rodape/index.jsx
  src/hooks/useErros.js
  src/index.js
  src/pages/CadastroMarca.jsx
  src/pages/ListagemMarcas.jsx
  src/reportWebVitals.js
  src/services/MarcaService.js
  src/services/VeiculoService.js
Labels: enhancement

#5 Listagem marca teste
  .eslintrc.json
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/index.js
  src/pages/CadastroMarca.jsx
  src/pages/CadastroMarca.test.js
  src/pages/ListagemMarcas.jsx
  src/pages/ListagemMarcas.test.js
  src/services/Marca/MarcaService.js
  src/services/Marca/MarcaService.test.js
  src/services/Veiculo/VeiculoService.js
  src/services/Veiculo/VeiculoService.test.js
Labels: enhancement

#16 Adição da tela de autenticação do usuário
  package-lock.json
  package.json
  src/App.js
  src/pages/Login.jsx
  src/pages/Login.test.js
  src/services/Auth/AuthService.js
  src/services/Auth/AuthService.test.js
Labels: Usuário, enhancement

#17 Feature/listagem de usuarios
  db.json
  package.json
  src/App.js
  src/App.test.js
  src/components/Listagem/Listagem.jsx
  src/components/Listagem/index.js
  src/pages/CadastroMarca/CadastroMarca.test.js
  src/pages/ListagemMarca/ListagemMarcas.jsx
  src/pages/ListagemMarca/ListagemMarcas.test.js
  src/pages/ListagemUsuario/ListagemUsuario.jsx
  src/pages/ListagemUsuario/ListagemUsuario.test.js
  src/pages/ListagemUsuario/index.js
  src/pages/ListagemVeiculos/ListagemVeiculos.jsx
  src/pages/ListagemVeiculos/ListagemVeiculos.test.js
  src/pages/ListagemVeiculos/index.js
  src/pages/Login/Login.test.js
  src/services/UsuarioService/UsuarioService.js
  src/services/UsuarioService/UsuarioService.test.js
  src/services/Veiculo/VeiculoService.js
  src/services/Veiculo/VeiculoService.test.js
Labels: Usuário, Veículo

#19 Feature/autenticacao
  .eslintignore
  .prettierrc
  .vscode/settings.json
  package.json
  sonar-project.properties
  src/App.js
  src/pages/Login/index.js
  src/pages/Usuarios/Cadastro/Cadastro.jsx
  src/pages/Usuarios/Cadastro/Cadastro.test.js
  src/pages/Usuarios/Cadastro/index.js
  src/pages/Usuarios/Login/Login.jsx
  src/pages/Usuarios/Login/Login.test.js
  src/pages/Usuarios/Login/index.js
  src/pages/Usuarios/index.js
  src/pages/Usuarios/validacoes.js
  src/services/Auth/AuthService.js
  src/services/Auth/AuthService.test.js
  src/tests/index.js
  src/tests/testing.js
  src/tests/usuarios.js
Labels: Usuário, enhancement

#21 Feature/cadastro alteracao veiculos
  .eslintrc.json
  .vscode/settings.json
  db.json
  src/App.js
  src/pages/ListagemUsuario/index.js
  src/pages/ListagemVeiculos/index.js
  src/pages/Marca/CadastroMarca/CadastroMarca.jsx
  src/pages/Marca/CadastroMarca/CadastroMarca.test.js
  src/pages/Marca/CadastroMarca/index.js
  src/pages/Marca/ListagemMarca/ListagemMarcas.jsx
  src/pages/Marca/ListagemMarca/ListagemMarcas.test.js
  src/pages/Marca/ListagemMarca/index.js
  src/pages/Marca/index.js
  src/pages/Usuarios/ListagemUsuario/ListagemUsuario.jsx
  src/pages/Usuarios/ListagemUsuario/ListagemUsuario.test.js
  src/pages/Usuarios/index.js
  src/pages/Usuarios/validacoes.js
  src/pages/Veiculos/CadastroVeiculos/CadastroVeiculos.jsx
  src/pages/Veiculos/CadastroVeiculos/CadastroVeiculos.test.js
  src/pages/Veiculos/ListagemVeiculos/ListagemVeiculos.jsx
  src/pages/Veiculos/ListagemVeiculos/ListagemVeiculos.test.js
  src/pages/Veiculos/index.js
Labels: Veículo
